//! 関数の一覧(名前・分類・引数・説明)。**このファイルは手で書かない** —
//! `python3 calc/gen_funcs.py > calc/src/funcs.rs` が
//! Euro-Office の formula-lang/ja_desc.json(本家の日本語)から起こす。
//! 載っているのは calc が実際に計算できる関数だけ。

pub struct FnInfo {
    pub name: &'static str,
    pub group: &'static str,
    pub args: &'static str,
    pub desc: &'static str,
}

pub static FUNCS: &[FnInfo] = &[  // 188 関数
    FnInfo { name: "ABS", group: "数学", args: "(数値)", desc: "数値から符号 (+、-) を除いた絶対値を返します。" },
    FnInfo { name: "ACOS", group: "数学", args: "(数値)", desc: "数値のアークコサインを返します。戻り値の角度は、0 (ゼロ)  ～ PI の範囲のラジアンとなります。アークコサインとは、そのコサインが数値であるような角度のことです。" },
    FnInfo { name: "ADDRESS", group: "検索", args: "(行番号, 列番号, [参照の種類], [参照形式], [シート名])", desc: "指定したセルの参照を文字列の形式で返します。" },
    FnInfo { name: "AND", group: "論理", args: "(論理式1, [論理式2], ...)", desc: "すべての引数が TRUE のとき、TRUE を返します。" },
    FnInfo { name: "ASC", group: "文字列", args: "(文字列)", desc: "2 バイト文字セット (DBCS) 言語の場合、全角 (2 バイト) 文字を半角 (1 バイト) 文字に変更します。" },
    FnInfo { name: "ASIN", group: "数学", args: "(数値)", desc: "数値のアークサインを返します。戻り値の角度は、-PI/2 ～ PI/2 の範囲のラジアンとなります。" },
    FnInfo { name: "ATAN", group: "数学", args: "(数値)", desc: "数値のアークタンジェントを返します。戻り値の角度は、-PI/2 ～ PI/2 の範囲のラジアンとなります。" },
    FnInfo { name: "ATAN2", group: "数学", args: "(x座標, y座標)", desc: "指定された x-y 座標のアークタンジェントを返します。戻り値の角度は、-PI から PI (ただし -PI を除く) の範囲のラジアンとなります。" },
    FnInfo { name: "AVERAGE", group: "統計", args: "(数値1, [数値2], ...)", desc: "引数の平均値を返します。引数には、数値、数値を含む名前、配列、セル参照を指定できます。" },
    FnInfo { name: "AVERAGEA", group: "統計", args: "(値1, [値2], ...)", desc: "引数の平均値を返します。引数の文字列および FALSE は 0、TRUE は 1 と見なします。引数には、数値、名前、配列、参照を含むことができます" },
    FnInfo { name: "AVERAGEIF", group: "統計", args: "(範囲, 条件, [平均対象範囲])", desc: "特定の条件に一致する数値の平均 (算術平均) を計算します" },
    FnInfo { name: "AVERAGEIFS", group: "統計", args: "(平均対象範囲, 条件範囲, 条件, ...)", desc: "特定の条件に一致する数値の平均 (算術平均) を計算します" },
    FnInfo { name: "CEILING", group: "数学", args: "(数値, 基準値)", desc: "指定された基準値の倍数のうち、最も近い値に数値を切り上げます。" },
    FnInfo { name: "CEILING.MATH", group: "数学", args: "(数値, [基準値], [モード])", desc: "数値を最も近い整数、または最も近い基準値の倍数に切り上げます。" },
    FnInfo { name: "CHAR", group: "文字列", args: "(数値)", desc: "使っているコンピューターの文字セットから、そのコード番号に対応する文字を返します。" },
    FnInfo { name: "CHOOSE", group: "検索", args: "(インデックス, 値1, [値2], ...)", desc: "インデックスを使って、引数リストから特定の値または動作を 1 つ選択します。" },
    FnInfo { name: "CLEAN", group: "文字列", args: "(文字列)", desc: "印刷できない文字を文字列から削除します。" },
    FnInfo { name: "CODE", group: "文字列", args: "(文字列)", desc: "文字列の先頭文字を表す数値コードを返します。" },
    FnInfo { name: "COLUMN", group: "検索", args: "([参照])", desc: "参照の列番号を返します。" },
    FnInfo { name: "COLUMNS", group: "検索", args: "(配列)", desc: "配列または参照の列数を返します。" },
    FnInfo { name: "COMBIN", group: "数学", args: "(総数, 抜き取り数)", desc: "すべての項目から指定された個数を選択するときの組み合わせの数を返します。" },
    FnInfo { name: "CONCAT", group: "文字列", args: "(テキスト1, ...)", desc: " テキスト文字列の一覧または範囲を連結します" },
    FnInfo { name: "CONCATENATE", group: "文字列", args: "(文字列1, [文字列2], ...)", desc: "複数の文字列を結合して 1 つの文字列にまとめます。" },
    FnInfo { name: "CORREL", group: "統計", args: "(配列1, 配列2)", desc: "2 つの配列の相関係数を返します。" },
    FnInfo { name: "COS", group: "数学", args: "(数値)", desc: "角度のコサインを返します。" },
    FnInfo { name: "COSH", group: "数学", args: "(数値)", desc: "数値の双曲線余弦を返します。" },
    FnInfo { name: "COUNT", group: "統計", args: "(値1, [値2], ...)", desc: "範囲内の、数値が含まれるセルの個数を返します。" },
    FnInfo { name: "COUNTA", group: "統計", args: "(値1, [値2], ...)", desc: "範囲内の、空白でないセルの個数を返します。" },
    FnInfo { name: "COUNTBLANK", group: "統計", args: "(範囲)", desc: "範囲に含まれる空白セルの個数を返します。" },
    FnInfo { name: "COUNTIF", group: "統計", args: "(範囲, 検索条件)", desc: "指定された範囲に含まれるセルのうち、検索条件に一致するセルの個数を返します。" },
    FnInfo { name: "COUNTIFS", group: "統計", args: "(検索条件範囲, 検索条件, ...)", desc: "特定の条件に一致するセルの個数を返します" },
    FnInfo { name: "DATE", group: "日付", args: "(年, 月, 日)", desc: "日付/時刻コードで指定した日付を表す数値を返します。" },
    FnInfo { name: "DATEDIF", group: "日付", args: "(開始日, 終了日, 単位)", desc: "2 つの日付の間の日数、月数、または年数を計算します。" },
    FnInfo { name: "DATESTRING", group: "文字列", args: "(シリアル値)", desc: "日付を和暦の文字列にして返します。" },
    FnInfo { name: "DATEVALUE", group: "日付", args: "(日付文字列)", desc: "文字列の形式で表された日付を、組み込みの日付表示形式で数値に変換して返します。" },
    FnInfo { name: "DAY", group: "日付", args: "(シリアル値)", desc: "シリアル値に対応する日を 1 から 31 までの整数で返します。" },
    FnInfo { name: "DAYS", group: "日付", args: "(終了日, 開始日)", desc: "2 つの日付の間の日数を返します。" },
    FnInfo { name: "DAYS360", group: "日付", args: "(開始日, 終了日, [方式])", desc: "1 年を 360 日として、指定した 2 つの日付の間の日数を返します。" },
    FnInfo { name: "DEGREES", group: "数学", args: "(角度)", desc: "ラジアンで表された角度を度に変更します。" },
    FnInfo { name: "EDATE", group: "日付", args: "(開始日, 月)", desc: "開始日から起算して、指定した月だけ前あるいは後の日付に対応するシリアル値を計算します。" },
    FnInfo { name: "EOMONTH", group: "日付", args: "(開始日, 月)", desc: "開始日から起算して、指定した月だけ前あるいは後の月の最終日に対応するシリアル値を計算します。" },
    FnInfo { name: "EVEN", group: "数学", args: "(数値)", desc: "指定した数値をもっとも近い偶数に切り上げた値を返します。" },
    FnInfo { name: "EXACT", group: "文字列", args: "(文字列1, 文字列2)", desc: "2 つの文字列を比較し、同じものであれば TRUE、異なれば FALSE を返します。EXACT 関数では、英字の大文字と小文字は区別されます。" },
    FnInfo { name: "EXP", group: "数学", args: "(数値)", desc: "e を底とする数値のべき乗を返します。" },
    FnInfo { name: "FACT", group: "数学", args: "(数値)", desc: "数値の階乗を返します。数値の階乗は、1 ～ 数値の範囲にある整数の積です。" },
    FnInfo { name: "FALSE", group: "論理", args: "()", desc: "論理値 FALSE を返します。" },
    FnInfo { name: "FILTER", group: "検索", args: "(配列, 含む, [空の場合])", desc: "範囲または配列をフィルターします" },
    FnInfo { name: "FIND", group: "文字列", args: "(検索文字列, 対象, [開始位置])", desc: "文字列が他の文字列内で最初に現れる位置を検索します。大文字と小文字は区別されます。" },
    FnInfo { name: "FIXED", group: "文字列", args: "(数値, [桁数], [桁区切り])", desc: "数値を指定された小数点で四捨五入し、コンマ (,) を使って、または使わずに書式設定した文字列に変換します。" },
    FnInfo { name: "FLOOR", group: "数学", args: "(数値, 基準値)", desc: "指定された基準値の倍数のうち、最も近い値に数値を切り捨てます。" },
    FnInfo { name: "FLOOR.MATH", group: "数学", args: "(数値, [基準値], [モード])", desc: "数値を最も近い整数、または最も近い基準値の倍数に切り下げます。" },
    FnInfo { name: "FORECAST", group: "統計", args: "(x, 既知のy, 既知のx)", desc: "既知の値を使用し、線形トレンドに沿って将来の値を予測します。" },
    FnInfo { name: "FV", group: "財務", args: "(利率, 期間, 定期支払額, [現在価値], [支払期日])", desc: "一定利率の支払いが定期的に行われる場合の、投資の将来価値を返します" },
    FnInfo { name: "GCD", group: "数学", args: "(数値1, [数値2], ...)", desc: "指定した数値の最大公約数を計算します。" },
    FnInfo { name: "HLOOKUP", group: "検索", args: "(検索値, 範囲, 行番号, [検索方法])", desc: "指定したテーブルまたは配列の先頭行で特定の値を検索し、指定した列と同じ行にある値を返します。" },
    FnInfo { name: "HOUR", group: "日付", args: "(シリアル値)", desc: "時刻を 0 (午前 0 時) ～ 23 (午後 11 時) の範囲の整数で返します。" },
    FnInfo { name: "HYPERLINK", group: "検索", args: "(リンク先, [別名])", desc: "ハード ディスク、ネットワーク サーバー、またはインターネット上に格納されているドキュメントを開くために、ショートカットまたはジャンプを作成します。" },
    FnInfo { name: "IF", group: "論理", args: "(論理式, [値が真の場合], [値が偽の場合])", desc: "論理式の結果 (真または偽) に応じて、指定された値を返します" },
    FnInfo { name: "IFERROR", group: "論理", args: "(値, エラーの場合の値)", desc: "式がエラーの場合は、エラーの場合の値を返します。エラーでない場合は、式の値自体を返します。" },
    FnInfo { name: "IFNA", group: "論理", args: "(値, NAの場合の値)", desc: "式が #N/A に解決される場合に指定する値を返します。それ以外の場合は、式の結果を返します。" },
    FnInfo { name: "IFS", group: "論理", args: "(論理式, 値が真の場合, ...)", desc: "1 つ以上の条件が満たされるかどうかを確認し、最初の真条件に対応する値を返します" },
    FnInfo { name: "INDEX", group: "検索", args: "(配列, 行番号, [列番号]!参照, 行番号, [列番号], [領域番号])", desc: "指定された行と列が交差する位置にある値またはセルの参照を返します。" },
    FnInfo { name: "INDIRECT", group: "検索", args: "(参照文字列, [参照形式])", desc: "指定される文字列への参照を返します。" },
    FnInfo { name: "INT", group: "数学", args: "(数値)", desc: "切り捨てて整数にした数値を返します。" },
    FnInfo { name: "INTERCEPT", group: "統計", args: "(既知のy, 既知のx)", desc: "既知の x と既知の y を通過する線形回帰直線の切片を計算します。" },
    FnInfo { name: "IRR", group: "財務", args: "(範囲, [推定値])", desc: "一連の定期的なキャッシュ フローに対する内部収益率を返します。" },
    FnInfo { name: "ISBLANK", group: "情報", args: "(テストの対象)", desc: "セルの内容が空白の場合に TRUE を返します。" },
    FnInfo { name: "ISERR", group: "情報", args: "(テストの対象)", desc: "セルの内容が #N/A 以外のエラー値の場合に TRUE を返します。" },
    FnInfo { name: "ISERROR", group: "情報", args: "(テストの対象)", desc: "セルの内容がエラー値の場合に TRUE を返します。" },
    FnInfo { name: "ISEVEN", group: "情報", args: "(数値)", desc: "引き数に指定した数値が偶数のとき TRUE を返し、奇数のとき FALSE を返します。" },
    FnInfo { name: "ISLOGICAL", group: "情報", args: "(テストの対象)", desc: "セルの内容が論理値 (TRUE または FALSE) の場合に TRUE を返します。" },
    FnInfo { name: "ISNA", group: "情報", args: "(テストの対象)", desc: "セルの内容がエラー値 #N/A の場合に TRUE を返します。" },
    FnInfo { name: "ISNONTEXT", group: "情報", args: "(テストの対象)", desc: "セルの内容が文字列以外の値 (空白セルも対象) である場合に TRUE を返します。" },
    FnInfo { name: "ISNUMBER", group: "情報", args: "(テストの対象)", desc: "セルの内容が数値の場合に TRUE を返します。" },
    FnInfo { name: "ISODD", group: "情報", args: "(数値)", desc: "引き数に指定した数値が奇数のとき TRUE を返し、偶数のとき FALSE を返します。" },
    FnInfo { name: "ISOWEEKNUM", group: "日付", args: "(日付)", desc: "指定された日付のその年における ISO 週番号を返します。" },
    FnInfo { name: "ISTEXT", group: "情報", args: "(テストの対象)", desc: "セルの内容が文字列である場合に TRUE を返します。" },
    FnInfo { name: "JIS", group: "文字列", args: "(文字列)", desc: "半角(1 バイト)文字を全角(2 バイト)文字に変換します。" },
    FnInfo { name: "LARGE", group: "統計", args: "(配列, 順位)", desc: "データの中から、指定した順位番目に大きな値を返します。" },
    FnInfo { name: "LCM", group: "数学", args: "(数値1, [数値2], ...)", desc: "指定した整数の最小公倍数を計算します。" },
    FnInfo { name: "LEFT", group: "文字列", args: "(文字列, [文字数])", desc: "文字列の先頭から指定された数の文字を返します。" },
    FnInfo { name: "LEFTB", group: "文字列", args: "(文字列, [文字数])", desc: "関数は、文字列の先頭から指定されたバイト数の文字を返します。関数は、2 バイト文字セット (DBCS) を使う言語での使用を前提としています。DBCS をサポートする言語には、日本語、中国語、および韓国語があります。" },
    FnInfo { name: "LEN", group: "文字列", args: "(文字列)", desc: "文字列の長さ (文字数) を返します。半角と全角の区別なく、1 文字を 1 として処理します。" },
    FnInfo { name: "LENB", group: "文字列", args: "(文字列)", desc: "関数は、文字列のバイト数を返します。関数は、2 バイト文字セット (DBCS) を使う言語での使用を前提としています。DBCS をサポートする言語には、日本語、中国語、および韓国語があります。" },
    FnInfo { name: "LN", group: "数学", args: "(数値)", desc: "数値の自然対数を返します。" },
    FnInfo { name: "LOG", group: "数学", args: "(数値, [底])", desc: "指定された数を底とする数値の対数を返します。" },
    FnInfo { name: "LOG10", group: "数学", args: "(数値)", desc: "引数の常用対数を返します。" },
    FnInfo { name: "LOOKUP", group: "検索", args: "(検査値, 検査範囲, [対応範囲]!検査値, 配列)", desc: "1 行または 1 列のみのセル範囲、または配列に含まれる値を返します。この関数は旧バージョンとの互換性を維持するためのものです。" },
    FnInfo { name: "LOWER", group: "文字列", args: "(文字列)", desc: "文字列に含まれる英字をすべて小文字に変換します。" },
    FnInfo { name: "MATCH", group: "検索", args: "(検査値, 検査範囲, [照合の種類])", desc: "指定された照合の種類に従って検査範囲内を検索し、検査値と一致する要素の、配列内での相対的な位置を表す数値を返します。" },
    FnInfo { name: "MAX", group: "統計", args: "(数値1, [数値2], ...)", desc: "引数の最大値を返します。論理値および文字列は無視されます。" },
    FnInfo { name: "MAXA", group: "統計", args: "(値1, [値2], ...)", desc: "引数の最大値を返します。論理値や文字列も対象となります。" },
    FnInfo { name: "MAXIFS", group: "統計", args: "(最大範囲, 条件範囲, 条件, ...)", desc: "所定の条件または基準で指定したセル間の最大値を返します" },
    FnInfo { name: "MEDIAN", group: "統計", args: "(数値1, [数値2], ...)", desc: "引数リストに含まれる数値のメジアン (中央値) を返します。" },
    FnInfo { name: "MID", group: "文字列", args: "(文字列, 開始位置, 文字数)", desc: "文字列の指定された位置から、指定された数の文字を返します。半角と全角の区別なく、1 文字を 1 として処理します。" },
    FnInfo { name: "MIDB", group: "文字列", args: "(文字列, 開始位置, 文字数)", desc: "関数は、文字列の任意の位置から指定されたバイト数の文字を返します。関数は、2 バイト文字セット (DBCS) を使う言語での使用を前提としています。DBCS をサポートする言語には、日本語、中国語、および韓国語があります。" },
    FnInfo { name: "MIN", group: "統計", args: "(数値1, [数値2], ...)", desc: "引数の最小値を返します。論理値および文字列は無視されます。" },
    FnInfo { name: "MINA", group: "統計", args: "(値1, [値2], ...)", desc: "引数の最小値を返します。論理値や文字列も対象となります。" },
    FnInfo { name: "MINIFS", group: "統計", args: "(最小範囲, 条件範囲, 条件, ...)", desc: "所定の条件または基準で指定したセル間の最小値を返します" },
    FnInfo { name: "MINUTE", group: "日付", args: "(シリアル値)", desc: "分を 0 ～ 59 の範囲の整数で返します。" },
    FnInfo { name: "MOD", group: "数学", args: "(数値, 除数)", desc: "数値を除算した剰余を返します。" },
    FnInfo { name: "MODE", group: "統計", args: "(数値1, [数値2], ...)", desc: "配列またはセル範囲として指定されたデータの中で、最も頻繁に出現する値 (最頻値) を返します。" },
    FnInfo { name: "MONTH", group: "日付", args: "(シリアル値)", desc: "月を 1 (1 月) ～ 12 (12 月) の範囲の整数で返します。" },
    FnInfo { name: "MROUND", group: "数学", args: "(数値, 倍数)", desc: "指定した値の倍数になるように数値の切り上げあるいは切り捨てを行います。" },
    FnInfo { name: "N", group: "情報", args: "(値)", desc: "非数値を数値に、日付をシリアル値に、TRUE の場合は 1 に、それ以外の場合は 0 に変換します。" },
    FnInfo { name: "NA", group: "情報", args: "()", desc: "エラー値 #N/A (値が無効) を返します。" },
    FnInfo { name: "NETWORKDAYS", group: "日付", args: "(開始日, 終了日, [祭日])", desc: "開始日と終了日の間にある週日の日数を計算します。" },
    FnInfo { name: "NOT", group: "論理", args: "(論理式)", desc: "引数が FALSE の場合は TRUE、TRUE の場合は FALSE を返します" },
    FnInfo { name: "NOW", group: "日付", args: "()", desc: "現在の日付と時刻を表すシリアル値を返します。" },
    FnInfo { name: "NPER", group: "財務", args: "(利率, 定期支払額, 現在価値, [将来価値], [支払期日])", desc: "一定利率の支払いが定期的に行われる場合の、ローンの支払回数を返します" },
    FnInfo { name: "NPV", group: "財務", args: "(割引率, 値1, [値2], ...)", desc: "投資の正味現在価値を、割引率、将来行われる一連の支払い (負の値)、およびその収益 (正の値) を使って算出します" },
    FnInfo { name: "NUMBERVALUE", group: "文字列", args: "(文字列, [小数点記号], [桁区切り記号])", desc: "文字列をロケールに依存しない方法で数値に変換します。" },
    FnInfo { name: "ODD", group: "数学", args: "(数値)", desc: "正の数値を切り上げ、負の数値を切り捨てて、最も近い奇数にします。" },
    FnInfo { name: "OFFSET", group: "検索", args: "(参照, 行数, 列数, [高さ], [幅])", desc: "指定した参照から指定した行数、列数の範囲への参照を返します。" },
    FnInfo { name: "OR", group: "論理", args: "(論理式1, [論理式2], ...)", desc: "いずれかの引数が TRUE のとき、TRUE を返します。引数がすべて FALSE である場合は、FALSE を返します。" },
    FnInfo { name: "PERCENTILE", group: "統計", args: "(配列, 率)", desc: "配列に含まれる値の k 番目の百分位を返します。" },
    FnInfo { name: "PERMUT", group: "数学", args: "(標本数, 抜き取り数)", desc: "指定した数の対象から、指定された数だけ抜き取る場合の順列の数を返します。" },
    FnInfo { name: "PHONETIC", group: "文字列", args: "(範囲)", desc: "セルのふりがなを返します(読み込んだ xlsx のふりがな情報を引きます)。" },
    FnInfo { name: "PI", group: "数学", args: "()", desc: "円周率π (3.14159265358979) を返します。" },
    FnInfo { name: "PMT", group: "財務", args: "(利率, 期間, 現在価値, [将来価値], [支払期日])", desc: "一定利率の支払いが定期的に行われる場合の、ローンの定期支払額を算出します" },
    FnInfo { name: "POWER", group: "数学", args: "(数値, 指数)", desc: "数値を累乗した値を返します。" },
    FnInfo { name: "PRODUCT", group: "数学", args: "(数値1, [数値2], ...)", desc: "引数の積を返します。" },
    FnInfo { name: "PROPER", group: "文字列", args: "(文字列)", desc: "文字列中の各単語の先頭文字を大文字に変換した結果を返します。" },
    FnInfo { name: "PV", group: "財務", args: "(利率, 期間, 定期支払額, [将来価値], [支払期日])", desc: "投資の現在価値を返します。現在価値とは、将来行われる一連の支払いを、現時点で一括払いした場合の合計金額のことをいいます" },
    FnInfo { name: "QUARTILE", group: "統計", args: "(配列, 戻り値)", desc: "配列に含まれるデータから四分位数を返します。" },
    FnInfo { name: "QUOTIENT", group: "数学", args: "(分子, 分母)", desc: "除算の商の整数部を返します。" },
    FnInfo { name: "RADIANS", group: "数学", args: "(角度)", desc: "度単位で表された角度をラジアンに変換した結果を返します。" },
    FnInfo { name: "RAND", group: "数学", args: "()", desc: "0 以上で 1 より小さい乱数を発生させます。再計算されるたびに、新しい乱数が返されます。" },
    FnInfo { name: "RANDBETWEEN", group: "数学", args: "(最小値, 最大値)", desc: "指定された範囲で一様に分布する整数の乱数を返します。" },
    FnInfo { name: "RANK", group: "統計", args: "(数値, 参照, [順序])", desc: "順序に従って範囲内の数値を並べ替えたとき、数値が何番目に位置するかを返します。" },
    FnInfo { name: "RANK.AVG", group: "統計", args: "(数値, 参照, [順序])", desc: "順序に従って範囲内の数値を並べ替えたとき、数値が何番目に位置するかを返します。複数の数値が同じ順位にある場合は、順位の平均を返します。" },
    FnInfo { name: "RANK.EQ", group: "統計", args: "(数値, 参照, [順序])", desc: "順序に従って範囲内の数値を並べ替えたとき、数値が何番目に位置するかを返します。複数の数値が同じ順位にある場合は、その値の中の最上位を返します。" },
    FnInfo { name: "RATE", group: "財務", args: "(期間, 定期支払額, 現在価値, [将来価値], [支払期日], [推定値])", desc: "ローンまたは投資の 1 期間あたりの利率を指定します。たとえば、年率 6% のローンを四半期払いで返済する場合、利率には 6%/4 = 1.5 (%) を指定します" },
    FnInfo { name: "REPT", group: "文字列", args: "(文字列, 繰り返し回数)", desc: "文字列を指定された回数だけ繰り返して表示します。この関数を使用して、セル幅全体に文字列を表示することができます。" },
    FnInfo { name: "RIGHT", group: "文字列", args: "(文字列, [文字数])", desc: "文字列の末尾から指定された文字数の文字を返します。" },
    FnInfo { name: "RIGHTB", group: "文字列", args: "(文字列, [バイト数])", desc: "関数は、文字列の末尾 (右端) から指定されたバイト数の文字を返します。関数は、2 バイト文字セット (DBCS) を使う言語での使用を前提としています。DBCS をサポートする言語には、日本語、中国語、および韓国語があります。" },
    FnInfo { name: "ROUND", group: "数学", args: "(数値, 桁数)", desc: "数値を指定した桁数に四捨五入した値を返します。" },
    FnInfo { name: "ROUNDDOWN", group: "数学", args: "(数値, 桁数)", desc: "数値を切り捨てます。" },
    FnInfo { name: "ROUNDUP", group: "数学", args: "(数値, 桁数)", desc: "数値を切り上げます。" },
    FnInfo { name: "ROW", group: "検索", args: "([参照])", desc: "参照の行番号を返します。" },
    FnInfo { name: "ROWS", group: "検索", args: "(配列)", desc: "参照、または配列に含まれる行数を返します。" },
    FnInfo { name: "SEARCH", group: "文字列", args: "(検索文字列, 対象, [開始位置])", desc: "文字列が最初に現れる位置の文字番号を返します。大文字、小文字は区別されません。" },
    FnInfo { name: "SECOND", group: "日付", args: "(シリアル値)", desc: "秒を 0 ～ 59 の範囲の整数で返します。" },
    FnInfo { name: "SEQUENCE", group: "数学", args: "(行, [列], [開始], [目盛り])", desc: "数列を返します。" },
    FnInfo { name: "SIGN", group: "数学", args: "(数値)", desc: "数値の正負を返します。戻り値は、数値が正の数のときは 1、0 のときは 0、負の数のときは -1 となります。" },
    FnInfo { name: "SIN", group: "数学", args: "(数値)", desc: "角度のサインを返します。" },
    FnInfo { name: "SINH", group: "数学", args: "(数値)", desc: "数値の双曲サインを返します。" },
    FnInfo { name: "SLOPE", group: "統計", args: "(既知のy, 既知のx)", desc: "指定されたデータ ポイントから線形回帰直線の傾きを返します。" },
    FnInfo { name: "SMALL", group: "統計", args: "(配列, 順位)", desc: "データの中から、指定した順位番目に小さな値を返します。" },
    FnInfo { name: "SORT", group: "検索", args: "(配列, [並べ替えインデックス], [並べ替え順序], [並べ替え基準])", desc: "範囲または配列を並べ替えます" },
    FnInfo { name: "SQRT", group: "数学", args: "(数値)", desc: "数値の正の平方根を返します。" },
    FnInfo { name: "STDEV", group: "統計", args: "(数値1, [数値2], ...)", desc: "標本に基づいて予測した標準偏差を返します。標本内の論理値と文字列は無視されます。" },
    FnInfo { name: "STDEVP", group: "統計", args: "(数値1, [数値2], ...)", desc: "引数を母集団全体であると見なして、母集団の標準偏差を返します。論理値、および文字列は無視されます。" },
    FnInfo { name: "SUBSTITUTE", group: "文字列", args: "(文字列, 検索文字列, 置換文字列, [置換対象])", desc: "文字列中の指定した文字を新しい文字で置き換えます。" },
    FnInfo { name: "SUBTOTAL", group: "数学", args: "(集計方法, 参照1, ...)", desc: "リストまたはデータベースの集計値を返します。" },
    FnInfo { name: "SUM", group: "数学", args: "(数値1, [数値2], ...)", desc: "セル範囲に含まれる数値をすべて合計します。" },
    FnInfo { name: "SUMIF", group: "統計", args: "(範囲, 検索条件, [合計範囲])", desc: "指定した検索条件に一致するセルの値を合計します" },
    FnInfo { name: "SUMIFS", group: "統計", args: "(合計対象範囲, 条件範囲, 条件, ...)", desc: "特定の条件に一致する数値の合計を求めます" },
    FnInfo { name: "SUMPRODUCT", group: "数学", args: "(配列1, [配列2], [配列3], ...)", desc: "範囲または配列の対応する要素の積を合計した結果を返します。" },
    FnInfo { name: "SUMSQ", group: "数学", args: "(数値1, [数値2], ...)", desc: "引数の 2 乗の和 (平方和) を返します。引数には、数値、数値を含む名前、配列、セル参照を指定できます。" },
    FnInfo { name: "SWITCH", group: "論理", args: "(式, 値1, 結果1, [既定または値2], [結果2], ...)", desc: " 値の一覧で式を計算し、最初に一致する値に対応する結果が返されます。一致しない場合は、任意の既定値が返されます" },
    FnInfo { name: "T", group: "情報", args: "(値)", desc: "値が文字列を参照する場合はその文字列を返し、文字列以外のデータを参照する場合は、空文字列 (\"\") を返します。" },
    FnInfo { name: "TAN", group: "数学", args: "(数値)", desc: "角度のタンジェントを返します。" },
    FnInfo { name: "TANH", group: "数学", args: "(数値)", desc: "数値の双曲タンジェントを返します。" },
    FnInfo { name: "TEXT", group: "文字列", args: "(値, 表示形式)", desc: "数値に指定した書式を設定し、文字列に変換した結果を返します。" },
    FnInfo { name: "TEXTJOIN", group: "文字列", args: "(区切り文字, 空のセルは無視, テキスト1, ...)", desc: " 区切り文字を使用してテキスト文字列の一覧または範囲を連結します" },
    FnInfo { name: "TIME", group: "日付", args: "(時, 分, 秒)", desc: "指定した時刻を表すシリアル値 (0:00:00 (午前 12:00:00) から 23:59:59 (午後 11:59:59) までを表す 0 から 0.9999999 の範囲の小数値) を返します。" },
    FnInfo { name: "TODAY", group: "日付", args: "()", desc: "現在の日付を表すシリアル値 (日付や時刻の計算で使用されるコード) を返します。" },
    FnInfo { name: "TRANSPOSE", group: "検索", args: "(配列)", desc: "配列の縦方向と横方向のセル範囲の変換を行います。" },
    FnInfo { name: "TRIM", group: "文字列", args: "(文字列)", desc: "単語間のスペースを 1 つずつ残して、不要なスペースをすべて削除します。" },
    FnInfo { name: "TRUE", group: "論理", args: "()", desc: "論理値 TRUE を返します。" },
    FnInfo { name: "TRUNC", group: "数学", args: "(数値, [桁数])", desc: "数値の小数部を切り捨てて、整数または指定した桁数に変換します。" },
    FnInfo { name: "TYPE", group: "情報", args: "(値)", desc: "値のデータ型を表す整数 (数値 = 1、文字列 = 2、論理値 = 4、エラー値 = 16、配列 = 64、複合データ = 128) を返します。" },
    FnInfo { name: "UNICHAR", group: "文字列", args: "(数値)", desc: "指定された数値により参照される Unicode 文字を返します。" },
    FnInfo { name: "UNICODE", group: "文字列", args: "(文字列)", desc: "文字列の最初の文字に対応する番号 (コード ポイント) を返します。" },
    FnInfo { name: "UNIQUE", group: "検索", args: "(配列, [列の比較], [回数指定])", desc: "範囲または配列から一意の値を返します" },
    FnInfo { name: "UPPER", group: "文字列", args: "(文字列)", desc: "文字列に含まれる英字をすべて大文字に変換します。" },
    FnInfo { name: "VALUE", group: "文字列", args: "(文字列)", desc: "文字列として入力されている数字を数値に変換します。" },
    FnInfo { name: "VAR", group: "統計", args: "(数値1, [数値2], ...)", desc: "標本に基づいて母集団の分散の推定値 (不偏分散) を返します。標本内の論理値と文字列は無視されます。" },
    FnInfo { name: "VARP", group: "統計", args: "(数値1, [数値2], ...)", desc: "引数を母集団全体と見なし、母集団の分散 (標本分散) を返します。論理値、および文字列は無視されます。" },
    FnInfo { name: "VLOOKUP", group: "検索", args: "(検索値, 範囲, 列番号, [検索方法])", desc: "指定された範囲の 1 列目で特定の値を検索し、指定した列と同じ行にある値を返します。テーブルは昇順で並べ替えておく必要があります。" },
    FnInfo { name: "WEEKDAY", group: "日付", args: "(シリアル値, [種類])", desc: "日付に対応する曜日を 1 から 7 までの整数で返します。" },
    FnInfo { name: "WEEKNUM", group: "日付", args: "(シリアル値, [週の基準])", desc: "日付がその年の第何週目に当たるかを返します。" },
    FnInfo { name: "WORKDAY", group: "日付", args: "(開始日, 日数, [祭日])", desc: "開始日から起算して日数で指定した日数だけ前あるいは後の日付に対応するシリアル値を計算します。" },
    FnInfo { name: "XLOOKUP", group: "検索", args: "(検索値, 検索範囲, 戻り範囲, [見つからない場合], [一致モード], [検索モード])", desc: "範囲または配列で一致の検索を行い、2 つめの範囲または配列から対応する項目を返します。既定では、完全一致が使用されます" },
    FnInfo { name: "YEAR", group: "日付", args: "(シリアル値)", desc: "年を 1900 ～ 9999 の範囲の整数で返します。" },
    FnInfo { name: "YEARFRAC", group: "日付", args: "(開始日, 終了日, [基準])", desc: "開始日から終了日までの間の日数を、年を単位とする数値で表します。" },
    FnInfo { name: "YEN", group: "文字列", args: "(数値, [桁数])", desc: "数値を円記号(¥)と桁区切りを付けた文字列にします。" },
];
